title: 'Freeplay Community'
default_lang: en
author:
  name: 'Freeplay staff'
  email: staff@freeplay.co
taxonomies:
  - game
  - company
  - person
metadata:
  description: 'Freeplay community - we talk about games '
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
description: 'We talk about games'
