title: 'Freeplay Community'
default_lang: en
author:
  name: 'Freeplay staff'
  email: staff@freeplay.com
  image: 
  bio: 'Playing games since forever'
taxonomies:
  - game
  - company
  - person
  - author
metadata:
  description: 'Freeplay - we talk about games'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
description: 'We talk about games'
logo: freeplay-logo.png
date_long: 'd F Y'
date_short: 'd M Y'
social:
  -
    icon: twitter
    url: 
    desc: 'Follow me on twitter'
    share_url: 'http://twitter.com/share'
    share_title: '?text='
    share_link: '&amp;url='
  -
    icon: facebook
    url: 
    desc: 'Connect with me facebook'
    share_url: 
    share_title: '?t='
    share_link: '&amp;u='
  -
    icon: github
    url: 
    desc: 'Fork me on github'
    share_url: null
    share_title: null
    share_link: null
  -
    icon: google-plus
    url: 
    desc: 'Add me on google+'
    share_url: null
    share_title: null
    share_link: null
